version: '3.8'
services:
  blog_veloder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    container_name: blog_veloder
    working_dir: /app
    command: python src/blog_veloder/main.py